[package]
name = "libaquestalk2-sys"
description = "Rust ffi for libaquestalk2"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.138"
